# base image - node:alpine
FROM node:10.15.3-alpine

# set the working directory to /app
WORKDIR /app

# install ganache-cli globally
RUN npm install -g ganache-cli

ARG BALANCE
# set the command ganache-cli -h 0.0.0.0
# for docker ganache-cli host on 0.0.0.0
CMD ["ganache-cli","-h","0.0.0.0","-m","-d"]